<a href="https://colab.research.google.com/github/GABRIELRANGELLEAL/Machine_learning/blob/main/Basico_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

# Sintaxe básica do Pytorch
Assim como o NumPy, o Pytorch é uma biblioteca de processamento vetorial/matricial/tensorial.
https://pytorch.org/docs/stable/tensors.html

## Tipos de tensores
Você pode criar tensores do PyTorch de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. O código para criar um tensor:

```
# a partir de uma lista
torch.Tensor(lista)

# a partir de um array numpy
torch.from_numpy(array)
```

In [2]:
# criando uma lista aleatória
lista = [[1,2,3],
         [4,5,6]
         ]
# criando tensor a partir da lista
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)
print('')

# quando queremos estabelecer o tipo dos elementos do tensor como float
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

# quando queremos estabelecer o tipo dos elementos do tensor como inteiros
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# criando array aleatório
arr = np.random.rand(3,4)
# mudando o tipo do array pra int
arr = arr.astype(int)
print('Tipo de dados do array:',arr.dtype)
print(arr)
print('')
# criando tensor a partir do array
tns = torch.from_numpy(arr)
print(tns)
print('Tipo de dados do tensor:',tns.dtype)

Tipo de dados do array: int64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
Tipo de dados do tensor: torch.int64


perceba que ele preserva o tipo de dados do array, o que não acontece quando geramos a partir de uma lista

## Tensores inicializados
Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

*torch.zeros(linhas,colunas)* -> Cria um tensor preenchido com zeros.

*torch.ones(linhas,colunas)* -> Cria um tensor preenchido com uns.

*torch.randn(linhas,colunas)* -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal

In [8]:
tns0 = torch.zeros(3,5)
tns1 = torch.ones(2,3)
tnsr = torch.randn(3,5)
print(tns0)
print(tns1)
print(tnsr)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-1.6742, -0.0529, -0.5032,  0.7079, -0.2999],
        [ 1.1507, -0.6225,  0.9903,  0.2401, -1.2630],
        [-0.6793, -0.7915,  1.1222,  0.0173, -1.4445]])


In [13]:
# da pra criar um tensor no torch e passar pra numpy tmb
arr = tnsr.data.numpy() # utilizamos o tensor aleatório que criamos acima
print(arr)
print(type(arr))

[[-1.6741691  -0.05293682 -0.50316846  0.70789266 -0.29989228]
 [ 1.1507387  -0.6224581   0.9902638   0.24012671 -1.2630492 ]
 [-0.67928326 -0.79150265  1.1222335   0.01725468 -1.4445364 ]]
<class 'numpy.ndarray'>


## Indexação
De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de colchetes [].

## Operações com tensores
A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as operações numéricas do Python. Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas ponto a ponto, operando cada elemento (i, j) do tensor t1, com o elemento (i, j) do tensor t2.

## Função .size() e .view()
Uma operações importantíssima na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, linearizar um tensor n-dimensional.

## GPU Cast
Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores na GPU, como os pesos da rede, os gradientes, etc.